### ISSUE TITLE
Cannot find name 'Buffer'

### ISSUE THREAD

**Issue by kamilwasyl** [akveo/ng2-smart-table#140]
error_handler.js:54 EXCEPTION: Uncaught (in promise): Error: Module build failed: Error: C:/Repository/op_frontend/node_modules/ng2-smart-table/src/ng2-smart-table/lib/helpers.ts (3,20): Cannot find name 'Buffer'.)
C:/Repository/op_frontend/node_modules/ng2-smart-table/src/ng2-smart-table/lib/helpers.ts (10,22): Cannot find name 'Buffer'.)
C:/Repository/op_frontend/node_modules/ng2-smart-table/src/ng2-smart-table/lib/helpers.ts (11,17): Cannot find name 'Buffer'.)
    at _checkDiagnostics (C:\Repository\op_frontend\node_modules\@ngtools\webpack\src\loader.js:145:15)
    at C:\Repository\op_frontend\node_modules\@ngtools\webpack\src\loader.js:172:17
Error: Module build failed: Error: C:/Repository/op_frontend/node_modules/ng2-smart-table/src/ng2-smart-table/lib/helpers.ts (3,20): Cannot find name 'Buffer'.)
C:/Repository/op_frontend/node_modules/ng2-smart-table/src/ng2-smart-table/lib/helpers.ts (10,22): Cannot find name 'Buffer'.)
C:/Repository/op_frontend/node_modules/ng2-smart-table/src/ng2-smart-table/lib/helpers.ts (11,17): Cannot find name 'Buffer'.)
    at _checkDiagnostics (C:\Repository\op_frontend\node_modules\@ngtools\webpack\src\loader.js:145:15)
    at C:\Repository\op_frontend\node_modules\@ngtools\webpack\src\loader.js:172:17
    at Object.<anonymous> (http://localhost:4200/0.chunk.js:18268:7) [angular]
    at __webpack_require__ (http://localhost:4200/inline.bundle.js:53:30) [angular]
    at Object.<anonymous> (http://localhost:4200/0.chunk.js:20049:67) [angular]
    at __webpack_require__ (http://localhost:4200/inline.bundle.js:53:30) [angular]
    at Object.<anonymous> (http://localhost:4200/0.chunk.js:20256:68) [angular]
    at __webpack_require__ (http://localhost:4200/inline.bundle.js:53:30) [angular]
    at Object.<anonymous> (http://localhost:4200/0.chunk.js:20004:101) [angular]
    at __webpack_require__ (http://localhost:4200/inline.bundle.js:53:30) [angular]
    at Object.<anonymous> (http://localhost:4200/0.chunk.js:23623:10) [angular]
    at __webpack_require__ (http://localhost:4200/inline.bundle.js:53:30) [angular]
    at Object.<anonymous> (http://localhost:4200/0.chunk.js:25:75) [angular]
    at __webpack_require__ (http://localhost:4200/inline.bundle.js:53:30) [angular]
    at http://localhost:4200/main.bundle.js:284:10 [angular]

what can I do ?

i ' ve added correctly : import { Ng2SmartTableModule } from 'ng2-smart-table';

plus in imports : Ng2SmartTableModule

**Comment by gsakhardande** [comment]
Even I am facing this issue

**Comment by LexZhukov** [comment]
Hi, @kamilwasyl. Could you try to install `@types/node`?

**Comment by gsakhardande** [comment]
@LexZhukov Thanks for your response. I am facing the same issue as @kamilwasyl and have `@types/node:"^6.0.42"` installed already.

**Comment by LexZhukov** [comment]
@gsakhardande, can you share your tsconfig?

**Comment by gsakhardande** [comment]
@LexZhukov: Please find the tsconfig below:

```
{
  "compilerOptions": {
    "baseUrl": "",
    "declaration": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": ["es6", "dom"],
    "mapRoot": "./",
    "module": "es6",
    "moduleResolution": "node",
    "outDir": "../dist/out-tsc",
    "sourceMap": true,
    "target": "es5",
    "typeRoots": [
      "../node_modules/@types"
    ]
  }
}
```

**Comment by LexZhukov** [comment]
@gsakhardande, try to set "lib": ["es2015", "dom"]

**Comment by nightwolfy** [comment]
@kamilwasyl as said there in [http://stackoverflow.com/a/38877890/3173865](stackoverflow) you can add `declare const Buffer` at the top and it should compile
