### ISSUE TITLE
Completer Editor on ng2-smart-table

### ISSUE THREAD

**Issue by mag1971** [akveo/ng2-smart-table#164]
When using the completer editor within the table I am able to use it once, it  shows the list for the input  value,  but if I delete the input content and try adding fresh values to the input no list is shown and I get following Error in browser console:

```
TypeError: Cannot read property 'title' of null
    at CellCompleterComponent.onEditedCompleter (http://localhost:4200/vendor.bundle.js:90799:35)
    at CompiledTemplate.proxyViewClass.View_CellCompleterComponent0.handleEvent_1 (/Ng2SmartTableModule/CellCompleterComponent/component.ngfactory.js:99:34)
    at CompiledTemplate.proxyViewClass.<anonymous> (http://localhost:4200/vendor.bundle.js:85749:37)
    at SafeSubscriber.schedulerFn [as _next] (http://localhost:4200/vendor.bundle.js:44426:36)
    at SafeSubscriber.__tryOrUnsub (http://localhost:4200/vendor.bundle.js:530:16)
    at SafeSubscriber.next (http://localhost:4200/vendor.bundle.js:479:22)
    at Subscriber._next (http://localhost:4200/vendor.bundle.js:432:26)
    at Subscriber.next (http://localhost:4200/vendor.bundle.js:396:18)
    at EventEmitter.Subject.next (http://localhost:4200/vendor.bundle.js:3593:25)
    at EventEmitter.emit (http://localhost:4200/vendor.bundle.js:44400:76)
    at http://localhost:4200/vendor.bundle.js:70260:28
    at SafeSubscriber.schedulerFn [as _next] (http://localhost:4200/vendor.bundle.js:44426:36)
    at SafeSubscriber.__tryOrUnsub (http://localhost:4200/vendor.bundle.js:530:16)
    at SafeSubscriber.next (http://localhost:4200/vendor.bundle.js:479:22)
    at Subscriber._next (http://localhost:4200/vendor.bundle.js:432:26)
ErrorHandler.handleError @ vendor.bundle.js:62094
```
I am installing with npm:
`npm install --save ng2-smart-table `

version in my package.json
**"ng2-smart-table": "^0.5.3-0"**

**Comment by mag1971** [comment]
Still having problems with this. Error output from console:
`EXCEPTION: Error in ./CompleterEditorComponent class CompleterEditorComponent - inline template:1:4 caused by: Cannot read property 'title' of null
ErrorHandler.handleError @ error_handler.js:54
next @ application_ref.js:348
schedulerFn @ async.js:93
SafeSubscriber.__tryOrUnsub @ Subscriber.js:223
SafeSubscriber.next @ Subscriber.js:172
Subscriber._next @ Subscriber.js:125
Subscriber.next @ Subscriber.js:89
Subject.next @ Subject.js:55
EventEmitter.emit @ async.js:79
NgZone.triggerError @ ng_zone.js:333
onHandleError @ ng_zone.js:294
webpackJsonp.982.ZoneDelegate.handleError @ zone.js:246
webpackJsonp.982.Zone.runTask @ zone.js:154
ZoneTask.invoke @ zone.js:345
error_handler.js:56 ORIGINAL EXCEPTION: Cannot read property 'title' of null
ErrorHandler.handleError @ error_handler.js:56
next @ application_ref.js:348
schedulerFn @ async.js:93
SafeSubscriber.__tryOrUnsub @ Subscriber.js:223
SafeSubscriber.next @ Subscriber.js:172
Subscriber._next @ Subscriber.js:125
Subscriber.next @ Subscriber.js:89
Subject.next @ Subject.js:55
EventEmitter.emit @ async.js:79
NgZone.triggerError @ ng_zone.js:333
onHandleError @ ng_zone.js:294
webpackJsonp.982.ZoneDelegate.handleError @ zone.js:246
webpackJsonp.982.Zone.runTask @ zone.js:154
ZoneTask.invoke @ zone.js:345
error_handler.js:59 ORIGINAL STACKTRACE:
ErrorHandler.handleError @ error_handler.js:59
next @ application_ref.js:348
schedulerFn @ async.js:93
SafeSubscriber.__tryOrUnsub @ Subscriber.js:223
SafeSubscriber.next @ Subscriber.js:172
Subscriber._next @ Subscriber.js:125
Subscriber.next @ Subscriber.js:89
Subject.next @ Subject.js:55
EventEmitter.emit @ async.js:79
NgZone.triggerError @ ng_zone.js:333
onHandleError @ ng_zone.js:294
webpackJsonp.982.ZoneDelegate.handleError @ zone.js:246
webpackJsonp.982.Zone.runTask @ zone.js:154
ZoneTask.invoke @ zone.js:345
error_handler.js:60 TypeError: Cannot read property 'title' of null
    at CompleterEditorComponent.onEditedCompleter (completer-editor.component.ts:35)
    at CompiledTemplate.proxyViewClass.View_CompleterEditorComponent0.handleEvent_1 (/Ng2SmartTableModule/CompleterEditorComponent/component.ngfactory.js:99)
    at CompiledTemplate.proxyViewClass.<anonymous> (view.js:664)
    at SafeSubscriber.schedulerFn [as _next] (async.js:105)
    at SafeSubscriber.__tryOrUnsub (Subscriber.js:223)
    at SafeSubscriber.next (Subscriber.js:172)
    at Subscriber._next (Subscriber.js:125)
    at Subscriber.next (Subscriber.js:89)
    at EventEmitter.Subject.next (Subject.js:55)
    at EventEmitter.emit (async.js:79)
    at completer-cmp.js:75
    at SafeSubscriber.schedulerFn [as _next] (async.js:105)
    at SafeSubscriber.__tryOrUnsub (Subscriber.js:223)
    at SafeSubscriber.next (Subscriber.js:172)
    at Subscriber._next (Subscriber.js:125)`

could someone confirm if this is a bug or have I missed something, a node module perhaps, that would fix this.

Thanks
Mike

**Comment by mag1971** [comment]
Thanks @LexZhukov
