### ISSUE TITLE
in my npm install still i'm getting "ng2-smart-table": "^0.6.0-1",

### ISSUE THREAD

**Issue by maheshp212** [akveo/ng2-smart-table#268]
I'm using the angular 4 and i'm getting the below error.

please help

./~/ng2-smart-table/src/ng2-smart-table.directives.ts
Module build failed: Error
    at new FatalError (/var/www/html/ims_app/trunk/web-app/node_modules/tslint/lib/error.js:40:23)
    at Function.findConfiguration (/var/www/html/ims_app/trunk/web-app/node_modules/tslint/lib/configuration.js:47:15)
    at resolveOptions (/var/www/html/ims_app/trunk/web-app/node_modules/tslint-loader/index.js:35:64)
    at Object.module.exports (/var/www/html/ims_app/trunk/web-app/node_modules/tslint-loader/index.js:124:17)
 @ ./~/ng2-smart-table/ng2-smart-table.js 5:9-52
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi (webpack)-dev-server/client?http://localhost:8080 ./src/main.ts

**Comment by LexZhukov** [comment]
@maheshp212 try to write in console `npm i -S ng2-smart-table@latest` or `npm i -S ng2-smart-table@1.0.1`.

**Comment by AndreiDev** [comment]
@maheshp212 any luck with this issue?
