### ISSUE TITLE
ang 2.3 support?

### ISSUE THREAD

**Issue by davidmontgom** [akveo/ng2-smart-table#289]
DUDES..docs on how to work with ang 2.3?

**Comment by davidmontgom** [comment]
This is what happens..  so rather concerned about using your product




Regex

Hide network

Hide violations
All
Errors
Warnings
Info
Logs
Debug
Handled
﻿
main.bundle.js:159451 Unhandled Promise rejection: Template parse errors:
'ng-template' is not a known element:
1. If 'ng-template' is an Angular component, then verify that it is part of this module.
2. If 'ng-template' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message. ("
    [ERROR ->]<ng-template #dynamicTarget></ng-template>
  "): CustomEditComponent@1:4 ; Zone: <root> ; Task: Promise.then ; Value: 
SyntaxError
 Error: Template parse errors:
'ng-template' is not a known element:
1. If 'ng-template' is an Angular component, then verify that it is part of this module.
2. If 'ng-template' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message. ("
    [ERROR ->]<ng-template #dynamicTarget></ng-template>
  "): CustomEditComponent@1:4
    at SyntaxError.BaseError [as constructor] (http://localhost:4200/main.bundle.js:115879:27)
    at new SyntaxError (http://localhost:4200/main.bundle.js:7109:16)
    at TemplateParser.parse (http://localhost:4200/main.bundle.js:39582:19)
    at JitCompiler._compileTemplate (http://localhost:4200/main.bundle.js:78267:68)
    at http://localhost:4200/main.bundle.js:78150:62
    at Set.forEach (native)
    at JitCompiler._compileComponents (http://localhost:4200/main.bundle.js:78150:19)
    at createResult (http://localhost:4200/main.bundle.js:78032:19)
    at ZoneDelegate.invoke (http://localhost:4200/main.bundle.js:159295:26)
    at Zone.run (http://localhost:4200/main.bundle.js:159177:43)

**Comment by lexzhukov** [comment]
@davidmontgom please take a look at https://github.com/akveo/ng2-smart-table/issues/266

**Comment by csharpcleancode** [comment]
**Here is the Solution** 
I got the same problem, and the issue is that you have to include import
{ Ng2SmartTableModule } from 'ng2-smart-table';
in your module file and don't forget to add it also in your imports on @NgModule
