### ISSUE TITLE
Can't import Ng2SmartTableModule

### ISSUE THREAD

**Issue by federhico** [akveo/ng2-smart-table#482]
i'm having problems to import this module.
after npm install 
I added 

`'ng2-smart-table':'npm:ng2-smart-table/bundles/table.umd.js'`

to my map object in systemjs.config.js

No problems yet.

even when i do the import in the app.module.ts

`import { Ng2SmartTableModule } from 'ng2-smart-table';`

I still having no problems.

But, when i add the module to the declarations array of the app.module.ts

`    declarations: [ ... , Ng2SmartTableModule],`

When i hit F5 (yes i'm in visual studio community 2017 with a Backend in .Net Core)

In the explorer (Chrome). I get  

```
(index):17 Error: (SystemJS) Unexpected token <
	SyntaxError: Unexpected token <
	    at eval (<anonymous>)
	    at Object.eval (http://localhost:3637/app/app.module.js:24:25)
	    at eval (http://localhost:3637/app/app.module.js:40:4)
	Evaluating http://localhost:3637/ng2-completer
	Evaluating http://localhost:3637/app/app.module.js
	Evaluating http://localhost:3637/app/main.js
	Error loading http://localhost:3637/app/main.js
	    at eval (<anonymous>)
	    at Object.eval (http://localhost:3637/app/app.module.js:24:25)
	    at eval (http://localhost:3637/app/app.module.js:40:4)
	Evaluating http://localhost:3637/ng2-completer
	Evaluating http://localhost:3637/app/app.module.js
	Evaluating http://localhost:3637/app/main.js
	Error loading http://localhost:3637/app/main.js
```

i'm doing something wrong ?

The app.module:24 ref is pointing to 
`var ng2_smart_table_1 = require("ng2-smart-table");`

Help please !

**Comment by federhico** [comment]
I fix it, was a problem with the dependencies.
Maybe is needed to add the information about this in the Doc's.

the dependencies are 

    "lodash": "^4.17.4",
    "ng2-completer": "^1.2.2",

And, if you are using Typescript with a systemjs config file, you must add the correct map and packages declaration:

```
map 
{
            'ng2-completer': 'npm:ng2-completer/ng2-completer.umd.js',
            'ng2-smart-table': 'npm:ng2-smart-table/bundles/table.umd.js',
            'lodash': 'npm:lodash'
}

packages{ 'lodash': { main: 'index.js', defaultExtension: 'js' }}
```
I hope i'm helping someone with this 👍
