### ISSUE TITLE
 I import Ng2SmartTableModule in app.module when I do npm start it has this error

### ISSUE THREAD

**Issue by dieToLoseWeight** [akveo/ng2-smart-table#66]
/~/ng2-smart-table/build/src/ng2-smart-table/components/cell/cell.scss
Module parse failed: D:\Users\710010336\Desktop\ng2\node_modules\ng2-smart-table\build\src\ng2-smart-table\components\cell\cell.scss Unexpected token (1:6)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (1:6)
    at Parser.pp$4.raise (D:\Users\710010336\Desktop\ng2\node_modules\acorn\dist\acorn.js:2221:15)
    at Parser.pp.unexpected (D:\Users\710010336\Desktop\ng2\node_modules\acorn\dist\acorn.js:603:10)
    at Parser.pp.semicolon (D:\Users\710010336\Desktop\ng2\node_modules\acorn\dist\acorn.js:581:61)
    at Parser.pp$1.parseExpressionStatement (D:\Users\710010336\Desktop\ng2\node_modules\acorn\dist\acorn.js:966:10)
    at Parser.pp$1.parseStatement (D:\Users\710010336\Desktop\ng2\node_modules\acorn\dist\acorn.js:730:24)
    at Parser.pp$1.parseTopLevel (D:\Users\710010336\Desktop\ng2\node_modules\acorn\dist\acorn.js:638:25)
    at Parser.parse (D:\Users\710010336\Desktop\ng2\node_modules\acorn\dist\acorn.js:516:17)
    at Object.parse (D:\Users\710010336\Desktop\ng2\node_modules\acorn\dist\acorn.js:3098:39)
    at Parser.parse (D:\Users\710010336\Desktop\ng2\node_modules\webpack\lib\Parser.js:902:15)
    at DependenciesBlock.<anonymous> (D:\Users\710010336\Desktop\ng2\node_modules\webpack\lib\NormalModule.js:104:16)
    at DependenciesBlock.onModuleBuild (D:\Users\710010336\Desktop\ng2\node_modules\webpack-core\lib\NormalModuleMixin.js:310:10)
    at nextLoader (D:\Users\710010336\Desktop\ng2\node_modules\webpack-core\lib\NormalModuleMixin.js:275:25)
    at D:\Users\710010336\Desktop\ng2\node_modules\webpack-core\lib\NormalModuleMixin.js:259:5
    at Storage.finished (D:\Users\710010336\Desktop\ng2\node_modules\webpack\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:38:16)
    at D:\Users\710010336\Desktop\ng2\node_modules\graceful-fs\graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:445:3)
 @ ./~/ng2-smart-table/build/src/ng2-smart-table/components/cell/cell.component.js 49:21-43errors @ client?e36c:75sock.onmessage @ socket.js?e5d0:37EventTarget.dispatchEvent @ eventtarget.js?3e89:51(anonymous function) @ main.js?45b8:274SockJS._transportMessage @ main.js?45b8:272EventEmitter.emit @ emitter.js?927b:50WebSocketTransport.ws.onmessage @ websocket.js?c17e:35wrapFn @ zone.js?fad3:698ZoneDelegate.invokeTask @ zone.js?fad3:265Zone.runTask @ zone.js?fad3:154ZoneTask.invoke @ zone.js?fad3:335
client?e36c:75 ./~/ng2-smart-table/build/src/ng2-smart-table/ng2-smart-table.scss
Module parse failed: D:\Users\710010336\Desktop\ng2\node_modules\ng2-smart-table\build\src\ng2-smart-table\ng2-smart-table.scss Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (1:0)
    at Parser.pp$4.raise (D:\Users\710010336\Desktop\ng2\node_modules\acorn\dist\acorn.js:2221:15)
    at Parser.pp.unexpected (D:\Users\710010336\Desktop\ng2\node_modules\acorn\dist\acorn.js:603:10)
    at Parser.pp$3.parseExprAtom (D:\Users\710010336\Desktop\ng2\node_modules\acorn\dist\acorn.js:1822:12)
    at Parser.pp$3.parseExprSubscripts (D:\Users\710010336\Desktop\ng2\node_modules\acorn\dist\acorn.js:1715:21)
    at Parser.pp$3.parseMaybeUnary (D:\Users\710010336\Desktop\ng2\node_modules\acorn\dist\acorn.js:1692:19)
    at Parser.pp$3.parseExprOps (D:\Users\710010336\Desktop\ng2\node_modules\acorn\dist\acorn.js:1637:21)
    at Parser.pp$3.parseMaybeConditional (D:\Users\710010336\Desktop\ng2\node_modules\acorn\dist\acorn.js:1620:21)
    at Parser.pp$3.parseMaybeAssign (D:\Users\710010336\Desktop\ng2\node_modules\acorn\dist\acorn.js:1597:21)
    at Parser.pp$3.parseExpression (D:\Users\710010336\Desktop\ng2\node_modules\acorn\dist\acorn.js:1573:21)
    at Parser.pp$1.parseStatement (D:\Users\710010336\Desktop\ng2\node_modules\acorn\dist\acorn.js:727:47)
    at Parser.pp$1.parseTopLevel (D:\Users\710010336\Desktop\ng2\node_modules\acorn\dist\acorn.js:638:25)
    at Parser.parse (D:\Users\710010336\Desktop\ng2\node_modules\acorn\dist\acorn.js:516:17)
    at Object.parse (D:\Users\710010336\Desktop\ng2\node_modules\acorn\dist\acorn.js:3098:39)
    at Parser.parse (D:\Users\710010336\Desktop\ng2\node_modules\webpack\lib\Parser.js:902:15)
    at DependenciesBlock.<anonymous> (D:\Users\710010336\Desktop\ng2\node_modules\webpack\lib\NormalModule.js:104:16)
    at DependenciesBlock.onModuleBuild (D:\Users\710010336\Desktop\ng2\node_modules\webpack-core\lib\NormalModuleMixin.js:310:10)
 @ ./~/ng2-smart-table/build/src/ng2-smart-table/ng2-smart-table.component.js 208:21-54

**Comment by LexZhukov** [comment]
https://github.com/akveo/ng2-smart-table/issues/128
