### ISSUE TITLE
import into project

### ISSUE THREAD

**Issue by Sn3b** [akveo/ng2-smart-table#78]
Hi I'm trying to import this module into a project based on this [seed](https://github.com/NathanWalker/angular-seed-advanced), but I cannot figure out how to have it as a npm dependency, the configuration is just impossible... :(

So I've copied over the code of the smart table but I reach an error saying "buffer is not defined". What "buffer" is that?

**Comment by RampberryPi** [comment]
I ran into the same issue. Environment is Typescript with Webpack. Here is the stacktrace 

```
EXCEPTION: Uncaught (in promise): Error: Error in ./LandingComponent class LandingComponent - inline template:15:45 caused by: Buffer is not defined
ReferenceError: Buffer is not defined
    at isSpecificValue (http://localhost:3000/view/main.bundle.js:25759:28)
    at http://localhost:3000/view/main.bundle.js:25846:22
    at Array.forEach (native)
    at http://localhost:3000/view/main.bundle.js:25831:26
    at Array.forEach (native)
    at Object.exports.deepExtend (http://localhost:3000/view/main.bundle.js:25826:10)
    at Ng2SmartTableComponent.prepareSettings (http://localhost:3000/view/main.bundle.js:68524:26)
    at Ng2SmartTableComponent.initGrid (http://localhost:3000/view/main.bundle.js:68511:55)
    at Ng2SmartTableComponent.ngOnChanges (http://localhost:3000/view/main.bundle.js:68436:18)
    at Wrapper_Ng2SmartTableComponent.ngDoCheck (/Ng2SmartTableModule/Ng2SmartTableComponent/wrapper.ngfactory.js:47:18)

```
