### ISSUE TITLE
You may need an appropriate loader to handle this file type.

### ISSUE THREAD

**Issue by ahrobinson** [akveo/ng2-smart-table#85]
I get multiple errors like this when trying to import ng2-smart-table, following the documentation:

`ERROR in ./~/ng2-smart-table/build/src/ng2-smart-table/ng2-smart-table.scss
Module parse failed: /Users/alonrobinson/projects/GE/s_op/sop-ng2/node_modules/ng2-smart-table/build/src/ng2-smart-table/ng2-smart-table.scss Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (1:0)
    at Parser.pp$4.raise (/Users/alonrobinson/projects/GE/s_op/sop-ng2/node_modules/acorn/dist/acorn.js:2221:15)
    at Parser.pp.unexpected (/Users/alonrobinson/projects/GE/s_op/sop-ng2/node_modules/acorn/dist/acorn.js:603:10)
    at Parser.pp$3.parseExprAtom (/Users/alonrobinson/projects/GE/s_op/sop-ng2/node_modules/acorn/dist/acorn.js:1822:12)
    at Parser.pp$3.parseExprSubscripts (/Users/alonrobinson/projects/GE/s_op/sop-ng2/node_modules/acorn/dist/acorn.js:1715:21)
    at Parser.pp$3.parseMaybeUnary (/Users/alonrobinson/projects/GE/s_op/sop-ng2/node_modules/acorn/dist/acorn.js:1692:19)
    at Parser.pp$3.parseExprOps (/Users/alonrobinson/projects/GE/s_op/sop-ng2/node_modules/acorn/dist/acorn.js:1637:21)
    at Parser.pp$3.parseMaybeConditional (/Users/alonrobinson/projects/GE/s_op/sop-ng2/node_modules/acorn/dist/acorn.js:1620:21)
    at Parser.pp$3.parseMaybeAssign (/Users/alonrobinson/projects/GE/s_op/sop-ng2/node_modules/acorn/dist/acorn.js:1597:21)
    at Parser.pp$3.parseExpression (/Users/alonrobinson/projects/GE/s_op/sop-ng2/node_modules/acorn/dist/acorn.js:1573:21)
    at Parser.pp$1.parseStatement (/Users/alonrobinson/projects/GE/s_op/sop-ng2/node_modules/acorn/dist/acorn.js:727:47)
    at Parser.pp$1.parseTopLevel (/Users/alonrobinson/projects/GE/s_op/sop-ng2/node_modules/acorn/dist/acorn.js:638:25)
    at Parser.parse (/Users/alonrobinson/projects/GE/s_op/sop-ng2/node_modules/acorn/dist/acorn.js:516:17)
    at Object.parse (/Users/alonrobinson/projects/GE/s_op/sop-ng2/node_modules/acorn/dist/acorn.js:3098:39)
    at Parser.parse (/Users/alonrobinson/projects/GE/s_op/sop-ng2/node_modules/webpack/lib/Parser.js:902:15)
    at DependenciesBlock.<anonymous> (/Users/alonrobinson/projects/GE/s_op/sop-ng2/node_modules/webpack/lib/NormalModule.js:104:16)
    at DependenciesBlock.onModuleBuild (/Users/alonrobinson/projects/GE/s_op/sop-ng2/node_modules/webpack-core/lib/NormalModuleMixin.js:310:10)
 @ ./~/ng2-smart-table/build/src/ng2-smart-table/ng2-smart-table.component.js 208:21-54
`

**Comment by samir-kamble** [comment]
Me too facing same issue.
